[[instance]] # Basic server with a shortcutted /assets
port = 8080
addr = "0.0.0.0"
# host = "shit.com"
http = {
	status_404 = "./configs/not_found.html", # Settings the default error page
	request_body_limit = 4_194_304, # 4MiB
}
routes = [
	{
		path = "/",

		type = "Server",
		props = {
			directory = "www",
			directory_list = false,
		},
	},
	{
		path = "/storage",

		type = "Server",
		props = {
			directory = "www/storage",
			directory_list = true,
		},
	},
	{
		path = "/assets",

		type = "Server",
		props = {
			directory = "www/assets",
			directory_list = true,
		},
	},
	{
		path = "/images",

		type = "Server",
		props = {
			directory = "www/assets/images",
			directory_list = false,
		},
	},
	# Redirections
	{
		path = "/favicon.ico",
		type = "Redirect",
		props = {
			location = "/assets/images/web.svg",
			status = 302,
		},
	},
	{
		path = "/redirect/dark",
		type = "Redirect",
		props = {
			location = "/?dark",
			status = 302,
		},
	},
	{
		path = "/redirect/1337.ma",
		type = "Redirect",
		props = {
			location = "https://1337.ma",
			status = 302,
		},
	},
	{
		path = "/upload",

		type = "Upload",
		props = {
			directory = "www/storage",
		},
	},
]

[[instance]] # Common Gateway Interface Example
port = 8081
addr = "127.0.0.1"
http = {
	timeout = 600_000,
}
routes = [
	{
		path = "/cgi",
		
		type = "CGI",
		props = {
			directory = "www/cgi-bin/",
			interpreters = {
				py  = "/usr/bin/python3",
				sh  = "/usr/bin/bash",
				php  = "/usr/bin/php-cgi",

			},
		}
	}
]
